# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x ./cinema-spring-api/gradlew
    - name: Build with Gradle
      run: |
            cd cinema-spring-api
            ./gradlew assemble  
            cd ..
            cp cinema-spring-api/build/libs ./jar
            ls
            
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: cinema-api
        path: ../cinema-spring-api/build/libs
    - name: Publish artifact
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          cd cinema-spring-api
          ./gradlew publish
